import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
export function write(slug, html, outputDir = './output') {
  const dir = join(outputDir, 'src', 'pages');
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, `${slug}.astro`), `---\n// AUTO-GENERATED BY PSEO-ENGINE\n---\n${html}\n`, 'utf8');
}
