import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
export function write(slug, html, outputDir = './output') {
  const dir = join(outputDir, 'pages');
  mkdirSync(dir, { recursive: true });
  const jsx = `// AUTO-GENERATED BY PSEO-ENGINE\nexport default function Page() {\n  return <div dangerouslySetInnerHTML={{ __html: ${JSON.stringify(html)} }} />;\n}\nexport async function getStaticProps() {\n  return { props: {} };\n}\n`;
  writeFileSync(join(dir, `${slug.replace(/\//g, '-')}.jsx`), jsx, 'utf8');
}
