import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
export function write(slug, html, outputDir = './output') {
  const dir = join(outputDir, 'pages');
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, `${slug}.vue`), `<!-- AUTO-GENERATED BY PSEO-ENGINE -->\n<template><div v-html="content" /></template>\n<script setup>\nconst content = ${JSON.stringify(html)}\n</script>\n`, 'utf8');
}
